FROM centos:7

RUN yum update -y
RUN yum install wget -y
RUN yum install unzip -y
RUN yum install java -y
RUN wget https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.76/bin/apache-tomcat-8.5.76.zip
RUN unzip apache-tomcat-8.5.76.zip
COPY tomcat-users.xml /apache-tomcat-8.5.76/conf/
COPY context.xml /apache-tomcat-8.5.76/webapps/manager/META-INF/
COPY /var/lib/jenkins/workspace/Mav_01/gameoflife-web/target/gameoflife.war /apache-tomcat-8.5.76/webapps/

RUN chmod 777 /apache-tomcat-8.5.76/bin/startup.sh
RUN chmod 777 /apache-tomcat-8.5.76/bin/shutdown.sh
RUN chmod 777 /apache-tomcat-8.5.76/bin/catalina.sh

EXPOSE 8081

CMD ["/apache-tomcat-8.5.76/bin/catalina.sh","run"]
